### ISSUE TITLE
Update oj to a more up-to-date version

### ISSUE THREAD

**Issue by paulkoegel** [cognitect/transit-ruby#28]
## Problem statement
+ we use `transit-json` in a large Rails application.
+ like `transit-ruby`, some of the other gems we use also rely on the `oj` gem.
+ we could not update some of those gems because they require at least version 3 of `oj`, which conflicts with `transit-ruby`'s `oj` requirement ("~> 2.18").

## Proposed solution
+ I forked this gem and updated `oj` to `3.10.3` here: https://github.com/paulkoegel/transit-ruby to resolve our issue. Specs are still green.
+ I would be nice to get this change into the main repo.

---

## FYI: Related issue
+ The latest versions of `oj`, 3.10.5 and 3.10.6 (there is no 3.10.4), break the specs of `transit-json`. I assume this is an `oj` problem.

```
Failures:

  1) JSON exemplars reads what we expect from ../transit-format/examples/0.8/simple/doubles_interesting.json
     Failure/Error: assert { exemplar.expected_value == actual_value }

       Expected (exemplar.expected_value == actual_value), but
       [-3.14159, 3.14159, 400000000000.0, 299800000.0, 6.626e-34            ]
       [-3.14159, 3.14159, 400000000000.0, 299800000.0, 6.626000000000001e-34]
                                                        ^

           exemplar.expected_value is [-3.14159, 3.14159, 400000000000.0, 299800000.0, 6.626e-34]
           exemplar is #<struct Exemplar name="doubles_interesting", expected_value=[-3.14159, 3.14159, 400000000000.0, 299800000.0, 6.626e-34]>
           actual_value is [-3.14159, 3.14159, 400000000000.0, 299800000.0, 6.626000000000001e-34]
     Shared Example Group: "exemplars" called from ./spec/transit/exemplar_spec.rb:146
     # ./spec/transit/exemplar_spec.rb:135:in `block (2 levels) in verify_exemplar'
     # ./spec/transit/exemplar_spec.rb:133:in `open'
     # ./spec/transit/exemplar_spec.rb:133:in `block in verify_exemplar'

  2) JSON-VERBOSE exemplars reads what we expect from ../transit-format/examples/0.8/simple/doubles_interesting.verbose.json
     Failure/Error: assert { exemplar.expected_value == actual_value }

       Expected (exemplar.expected_value == actual_value), but
       [-3.14159, 3.14159, 400000000000.0, 299800000.0, 6.626e-34            ]
       [-3.14159, 3.14159, 400000000000.0, 299800000.0, 6.626000000000001e-34]
                                                        ^

           exemplar.expected_value is [-3.14159, 3.14159, 400000000000.0, 299800000.0, 6.626e-34]
           exemplar is #<struct Exemplar name="doubles_interesting", expected_value=[-3.14159, 3.14159, 400000000000.0, 299800000.0, 6.626e-34]>
           actual_value is [-3.14159, 3.14159, 400000000000.0, 299800000.0, 6.626000000000001e-34]
     Shared Example Group: "exemplars" called from ./spec/transit/exemplar_spec.rb:150
     # ./spec/transit/exemplar_spec.rb:135:in `block (2 levels) in verify_exemplar'
     # ./spec/transit/exemplar_spec.rb:133:in `open'
     # ./spec/transit/exemplar_spec.rb:133:in `block in verify_exemplar'

Finished in 0.58072 seconds (files took 0.52754 seconds to load)
909 examples, 2 failures

Failed examples:

rspec './spec/transit/exemplar_spec.rb[1:23]' # JSON exemplars reads what we expect from ../transit-format/examples/0.8/simple/doubles_interesting.json
rspec './spec/transit/exemplar_spec.rb[2:23]' # JSON-VERBOSE exemplars reads what we expect from ../transit-format/examples/0.8/simple/doubles_interesting.verbose.json
```

**Comment by paulkoegel** [comment]
with `oj` version `3.10.16` the `transit-ruby` specs are now green again for me (tested with Ruby version:
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin18])
